version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./EmsApp:/app/EmsApp
    environment:
      - SQLALCHEMY_DATABASE_URL=mysql+pymysql://username:password@mysql:3306/ems
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ems
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
      MYSQL_ROOT_PASSWORD: ""

      